# Generated by Django 3.1.7 on 2021-07-28 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support_user_sponser_detail',
            name='city',
            field=models.CharField(blank=True, choices=[('Agra', 'Agra'), ('Aligarh', 'Aligarh'), ('Allahabad', 'Allahabad'), ('Ambedkar Nagar', 'Ambedkar Nagar'), ('Amethi', 'Amethi'), ('Amroha', 'Amroha'), ('Auraiya', 'Auraiya'), ('Azamgarh', 'Azamgarh'), ('Baghpat', 'Baghpat'), ('Bahraich', 'Bahraich'), ('Ballia', 'Ballia'), ('Balrampur', 'Balrampur'), ('Banda', 'Banda'), ('Barabanki', 'Barabanki'), ('Bareilly', 'Bareilly'), ('Basti', 'Basti'), ('Bhadohi', 'Bhadohi'), ('Bijnor', 'Bijnor'), ('Budaun', 'Budaun'), ('Bulandshahr', 'Bulandshahr'), ('Chandauli', 'Chitrakoot'), ('Deoria', 'Deoria'), ('Etah', 'Etah'), ('Etawah', 'Etawah'), ('Faizabad', 'Faizabad'), ('Farrukhabad', 'Farrukhabad'), ('Fatehpur', 'Fatehpur'), ('Firozabad', 'Firozabad'), ('Gautam Buddha Nagar', 'Gautam Buddha Nagar'), ('Ghaziabad', 'Ghaziabad'), ('Ghazipur', 'Ghazipur'), ('Gonda', 'Gonda'), ('Gorakhpur', 'Gorakhpur'), ('Hamirpur', 'Hamirpur'), ('Hapur', 'Hapur'), ('Hardoi', 'Hardoi'), ('Hathras', 'Hathras'), ('Jalaun', 'Jalaun'), ('Jaunpur', 'Jaunpur'), ('Jhansi', 'Jhansi'), ('Kannauj', 'Kannauj'), ('Kanpur Dehat', 'Kanpur Dehat'), ('Kanpur Nagar', 'Kanpur Nagar'), ('Kanshiram Nagar', 'Kanshiram Nagar'), ('Kaushambi', 'Kaushambi'), ('Kushinagar', 'Kushinagar'), ('Lakhimpur ', 'Lakhimpur '), ('Lalitpur', 'Lalitpur'), ('Lucknow', 'Lucknow'), ('Maharajganj', 'Maharajganj'), ('Mahoba', 'Mahoba'), ('Mainpuri', 'Mainpuri'), ('Mathura', 'Mathura'), ('Mau', 'Mau'), ('Meerut', 'Meerut'), ('Mirzapur', 'Mirzapur'), ('Moradabad', 'Moradabad'), ('Muzaffarnagar', 'Muzaffarnagar'), ('Pilibhit', 'Pilibhit'), ('Pratapgarh', 'Pratapgarh'), ('RaeBareli', 'RaeBareli'), ('Rampur', 'Rampur'), ('Saharanpur', 'Saharanpur'), ('Sambhal ', 'Sambhal '), ('Sant Kabir Nagar', 'Sant Kabir Nagar'), ('Shahjahanpur', 'Shahjahanpur'), ('Shamali ', 'Shamali '), ('Shravasti', 'Shravasti'), ('Siddharth Nagar', 'Siddharth Nagar'), ('Sitapur', 'Sitapur'), ('Sonbhadra', 'Sonbhadra'), ('Sultanpur', 'Sultanpur'), ('Unnao', 'Unnao'), ('Varanasi', 'Varanasi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='support_user_sponser_detail',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='support_user_sponser_detail',
            name='recommended_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
