# Generated by Django 3.1.7 on 2021-07-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210729_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support_user_sponser_detail',
            name='sponser_id',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
