# Generated by Django 3.1.7 on 2021-07-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210729_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support_user_sponser_detail',
            name='recommended_by',
        ),
    ]
