# Generated by Django 3.1.7 on 2021-07-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_support_user_sponser_detail_recommended_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='support_user_sponser_detail',
            name='mobile_no',
            field=models.PositiveBigIntegerField(default='1234567890'),
        ),
    ]
