# Generated by Django 3.1.7 on 2021-07-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_support_user_sponser_detail_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support_user_sponser_detail',
            name='id',
        ),
        migrations.AlterField(
            model_name='support_user_sponser_detail',
            name='sponser_id',
            field=models.CharField(blank=True, max_length=6, primary_key=True, serialize=False),
        ),
    ]
